# Settings in the config.yml are overriding Squib's defaults. Anything in the main script will override this.

# DPI is used in making PDFs and in unit conversions
# Default: 300
#dpi: 72

antialias: best

#text_hint: '#F00'

#Enable some custom colors that can be used in any color
#custom_colors:
#  foo: '#abc'

img_dir: images

warn_ellipsize: true
warn_png_scale: true
